---
- name: Create directory
  win_file:
    path: "{{ winlogbeat_install_location }}"
    state: directory
  register: result

- name: Get winlogbeat zip
  win_get_url:
    url: "{{ winlogbeat_download_url_base }}/{{ winlogbeat_download_file }}{{ file_ext }}"
    dest: "{{ winlogbeat_install_location }}/{{ winlogbeat_download_file }}{{ file_ext }}"
  when: result.changed

- name: Unzip winlogbeat
  win_unzip:
    src: "{{ winlogbeat_install_location }}/{{ winlogbeat_download_file }}{{ file_ext }}"
    dest: "{{ winlogbeat_install_location }}"
  when: result.changed

- name: Install the service via script
  win_command: powershell.exe -ExecutionPolicy ByPass -File "{{ winlogbeat_install_location }}/{{ winlogbeat_download_file }}/install-service-winlogbeat.ps1"
  args:
    chdir: "{{ winlogbeat_install_location }}/{{ winlogbeat_download_file }}"
  when: result.changed

- name: Copy WinLogBeat configuration.
  win_template:
    src: winlogbeat.yml.j2
    dest: "{{ winlogbeat_install_location }}/{{ winlogbeat_download_file }}/winlogbeat.yml"
  notify: restart winlogbeat
